urbanshef/urls.py
from django.urls import path

from .views import StripeAuthorizeView, StripeAuthorizeCallbackView


urlpatterns = [
  path('authorize/', StripeAuthorizeView.as_view(), name='authorize'),
  path('oauth/callback/', StripeAuthorizeCallbackView.as_view(), name='authorize_callback'),
]

urbanshefapp/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from urbanshef import views, apis
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from django.conf import settings
from urbanshef.views import CustomPasswordResetView

schema_view = get_schema_view(
    openapi.Info(
        title="Slobite API",
        default_version='1.0',
        description="Slobite API Documentation",
        terms_of_service="https://www.slobite.com/privacy/",
        contact=openapi.Contact(email="developers@slobite.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    url='https://slobite.com'
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/users/', views.BrowseUsers, name='browse-user'),
    path('', views.index, name='home'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('food-safety/', views.food_safety, name='food-safety'),
    path('report-bugs/', views.report_bugs, name='report-bugs'),
    path('', include('urbanshef.urls')),

    # Chef
    path('chef/login/', views.LoginView.as_view(), name='chef-login'),
    path('chef/logout/', auth_views.LogoutView.as_view(next_page='/'), name='chef-logout'),
    path('chef/sign-up/', views.chef_sign_up, name='chef-sign-up'),
    path('become-a-chef/', views.BecomeAShef.as_view(), name='become-a-shef'),
    path('chef/reset_password/', CustomPasswordResetView.as_view(template_name='chef/password_reset.html'), name="reset_password"),

    path('chef/reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="chef/password_reset_sent.html"),
         name="password_reset_done"),

    path('chef/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='chef/password_reset_form.html'),
         name="password_reset_confirm"),

    path('chef/reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="chef/password_reset_done.html"),
         name="password_reset_complete"),

    path('chef/', views.chef_home, name='chef-home'),

    # Manage availablity
    path('updatechefavailability/', views.update_availability, name='update-availability'),
    path('checkavailability/', views.check_availability, name='check-availability'),

    path('chef/account/', views.chef_account, name='chef-account'),
    path('chef/meal/', views.chef_meal, name='chef-meal'),
    path('chef/meal/add/', views.chef_add_meal, name='chef-add-meal'),
    path('chef/meal/edit/<int:meal_id>/', views.chef_edit_meal, name='chef-edit-meal'),
    path('chef/order/', views.chef_order, name='chef-order'),
    path('chef/report/', views.chef_report, name='chef-report'),
    path('chef/review/', views.review, name='chef-review'),
    path('chef/review/reply/<int:review_id>', views.reply_to_review, name='chef-reply-review'),
    path('chef/onboarding-call/', login_required(login_url='/chef/login/')(views.CheckListView.as_view()), name='chef-onboarding-call'),

    # Sign In/ Sign Up/ Sign Out
    path('api/social/', include('drf_social_oauth2.urls', namespace='drf')),

    # /convert-token (sign in/ sign up)
    # /revoke-token (sign out)
    path('api/chef/order/notification/<int:last_request_time>/', apis.chef_order_notification),

    # # APIs for CUSTOMERS
    path('api/customer/chefs/', apis.CustomerGetChefs.as_view()),
    path('api/customer/meals/<int:chef_id>/', apis.CustomerGetMeals.as_view()),
    path('api/customer/allergens/<int:meal_id>/', apis.MealAllergens.as_view()),
    path('api/customer/order/add/', apis.CustomerAddAPIView.as_view()),
    path('api/customer/order/coupon/', apis.ApplyCoupon.as_view()),
    path('api/customer/order/latest/', apis.customer_get_latest_order.as_view()),
    path('api/customer/driver/location/', apis.customer_driver_location.as_view()),
    #
    # Payment securing
    path('api/customer/payment/sheet/', apis.PaymentSheet.as_view()),
    path('api/customer/payment/method/', apis.PaymentMethodCreate.as_view()),
    path('api/customer/payment/intent/create', apis.PaymentIntentCreate.as_view()),
    path('api/customer/payment/intent/check/', apis.PaymentIntentCheck.as_view()),
    path('api/customer/payment/intent/modify/', apis.PaymentIntentModify.as_view()),
    path('api/customer/payment/intent/confirm/', apis.PaymentIntentConfirm.as_view()),
    path('api/customer/payment/intent/cancel/', apis.PaymentIntentCancel.as_view()),
    # # APIs for DRIVERS
    path('api/driver/orders/ready/', apis.driver_get_ready_orders.as_view()),
    path('api/driver/order/pick/', apis.driver_pick_order),
    path('api/driver/order/latest/', apis.driver_get_latest_order),
    path('api/driver/order/complete/', apis.driver_complete_order),
    path('api/driver/revenue/', apis.driver_get_revenue),
    path('api/driver/location/update/', apis.driver_update_location),

    # Review API
    path('api/review/', apis.ReviewAPIView.as_view()),

    # Chef contact
    path('api/chef/contact/<pk>/', apis.ChefContactInfoAPIView.as_view()),

    # Chef Bio
    path('api/chef/bio/<pk>/', apis.ChefBioAPIView.as_view()),

    # Chef average review
    path('api/chef/review/<pk>/', apis.ChefAvgRatingAPIView.as_view()),

    path('api/chef/uk_food_rating/<chef_id>/', apis.ShefUKFoodRating.as_view()),

    path('doc/', schema_view.with_ui('swagger', cache_timeout=-25), name='schema-swagger-ui')

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'urbanshef.views.error_404_view'
admin.site.site_header = 'Slobite CRM'
admin.site.site_title = 'Slobite CRM'
admin.site.index_title = 'Slobite CRM'

urbanshef/models.py
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
# Create your models here.
from multiselectfield import MultiSelectField
from places.fields import PlacesField


class Chef(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='chef')
    name = models.CharField(max_length=500, blank=True)
    phone = models.CharField(max_length=500, blank=True)
    chef_street_address = PlacesField(blank=True)
    chef_flat_number = models.CharField(max_length=500, blank=True)
    city = models.CharField(max_length=500, blank=True)
    postcode = models.CharField(max_length=500, blank=True)
    picture = models.ImageField(upload_to='chef_logo/', blank=True)
    stripe_user_id = models.CharField(max_length=255, blank=True)
    stripe_access_token = models.CharField(max_length=255, blank=True)
    authorized_to_work_in_the_UK = models.BooleanField(default=False)
    available = models.BooleanField(default=False)
    level_2_food_hygiene_certificate = models.FileField(upload_to='chef_certificate/', blank=True, null=True)
    disabled_by_admin = models.BooleanField(default=True)
    note = models.TextField(null=True, blank=True)
    bio = models.TextField(blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=100, choices=(("Male", "Male"), ("Female", "Female"), ("Other", "Other")),
                              blank=True)
    agree_terms_and_condition = models.BooleanField()
    # Added on Demand
    delivery_time = models.CharField(max_length=255, blank=True, choices=(
        ('Pre-order', 'Pre-order'), ('30-60 min', '30-60 min'), ('60-120 min', '60-120 min')), default='Pre-order')
    # -------------
    cuisine = models.CharField(max_length=255, blank=True, choices=(
        ("British", "British"), ("Chinese", "Chinese"), ("Japanese", "Japanese"), ("Indian", "Indian"),
        ("Italian", "Italian"), ("Pakistani", "Pakistani"), ("Middle East", "Middle East"), ("Nepalese", "Nepalese"),
        ("Mexican", "Mexican"), ("Korean", "Korean"), ("African", "African"), ("Mediterranean", "Mediterranean"),
        ("Caribbean", "Caribbean"), ("French", "French"), ("Latin American", "Latin American"), ("Spanish", "Spanish"),
        ("South East Asian", "South East Asian"), ("European", "European")))
    status = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.id:
            chef = Chef.objects.get(id=self.id)
            if chef.disabled_by_admin == False and self.disabled_by_admin == True:
                send_mail('Slobite: Account Alert  ',
                          'Hello chef! Your account has been disabled by our chef operations team. Kindly, get in touch with us to discuss this matter urgently.',
                          'admin@slobite.com',
                          [chef.user.email], fail_silently=False)
            if chef.disabled_by_admin == True and self.disabled_by_admin == False:
                send_mail('Slobite: Account Alert',
                          'Hello chef! Great news. You account is now active. Start sharing your recipies safely with your neighbourhood. For any further assistance, please contact us at chef@slobite.com or by using the chat support on our website.',
                          'admin@slobite.com',
                          [chef.user.email], fail_silently=False)

        super(Chef, self).save()


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    customer_street_address = models.CharField(max_length=500)
    customer_flat_number = models.CharField(max_length=500)
    stripe_id = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.user.get_username()

    def first_name(self):
        return self.user.first_name

    def last_name(self):
        return self.user.last_name

    def email(self):
        return self.user.email


class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='driver')
    name = models.CharField(max_length=500)
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    location = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.user.get_full_name()


class Meal(models.Model):
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    short_description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='meal_images/', blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True,
                                help_text='A 20% tax will be automatically added to the price')
    portion_size = models.CharField(max_length=255, help_text="12 pieces or 12 oz. container or others", blank=True)
    food_type = models.CharField(max_length=255, choices=(
        ('Appetizer', 'Appetizer'), ('Main', 'Main'), ('Side', 'Side'), ('Dessert', 'Dessert')), default=0)
    # Added on demand
    spicy = models.CharField(max_length=255, choices=(
        ('Mild', 'Mild'), ('Medium', 'Medium'), ('Hot', 'Hot'), ('Extreme', 'Extreme')), blank=True, null=True)
    diet = models.CharField(max_length=255, choices=(
        ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')), blank=True, null=True)
    # --------------------
    allergen = MultiSelectField(choices=(
        ('Celery', 'Celery'), ('Gluten', 'Gluten'), ('Crustaceans', 'Crustaceans'), ('Eggs', 'Eggs'), ('Fish', 'Fish'),
        ('Lupin', 'Lupin'), ('Milk', 'Milk'), ('Molluscs', 'Molluscs'), ('Mustard', 'Mustard'), ('Peanuts', 'Peanuts'),
        ('Sesame', 'Sesame'), ('Soybeans', 'Soybeans'), ('Sulphur dioxide', 'Sulphur dioxide'),
        ('Sulphites', 'Sulphites'),
        ('Nuts', 'Nuts')), default=0)
    cuisine = models.CharField(max_length=255, choices=(
        ("British", "British"), ("Chinese", "Chinese"), ("Japanese", "Japanese"), ("Indian", "Indian"),
        ("Italian", "Italian"), ("Pakistani", "Pakistani"), ("Middle East", "Middle East"), ("Nepalese", "Nepalese"),
        ("Mexican", "Mexican"), ("Korean", "Korean"), ("African", "African"), ("Mediterranean", "Mediterranean"),
        ("Caribbean", "Caribbean"), ("French", "French"), ("Latin American", "Latin American"), ("Spanish", "Spanish"),
        ("South East Asian", "South East Asian"), ("European", "European")), default=0)
    availability = models.CharField(max_length=200,
                                    choices=(('Available', 'Available'), ('Unavailable', 'Unavailable')))

    def __str__(self):
        return self.name


class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    active = models.BooleanField()

    def __str__(self):
        return self.code


class Order(models.Model):
    COOKING = 1
    READY = 2
    ONTHEWAY = 3
    DELIVERED = 4

    STATUS_CHOICES = (
        (COOKING, "Cooking"),
        (READY, "Ready"),
        (ONTHEWAY, "On the way"),
        (DELIVERED, "Delivered"),
    )

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, blank=True, null=True, on_delete=models.CASCADE)
    customer_street_address = models.CharField(max_length=500)
    customer_flat_number = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    delivery_charge = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    service_charge = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    delivery_instructions = models.CharField(max_length=500, null=False, blank=True)
    status = models.IntegerField(choices=STATUS_CHOICES)
    created_at = models.DateTimeField(default=timezone.now)
    picked_at = models.DateTimeField(blank=True, null=True)
    coupon = models.ForeignKey(Coupon, related_name='order_coupon', to_field='code', blank=True, null=True,
                               on_delete=models.SET_NULL)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    pre_order = models.DateTimeField(null=True, blank=True)
    payment_id = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return str(self.id)


class OrderDetails(models.Model):
    order = models.ForeignKey(Order, related_name='order_details', on_delete=models.CASCADE)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=True, null=True)
    delivery_instructions = models.CharField(max_length=500, null=False, blank=True)
    delivery_charge = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    sub_total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return str(self.id)


class Review(models.Model):
    order = models.ForeignKey(Order, related_name='review_order', on_delete=models.CASCADE)
    chef = models.ForeignKey(Chef, related_name='review_chef', on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, related_name='review_customer', on_delete=models.CASCADE)
    rating = models.IntegerField(choices=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5)))

urbanshef/templates/chef/account.html
{% extends 'chef/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block title %} Profile Settings - Slobite {% endblock %}
{% block script %}
<style>
    .places {
        display: none;
        width: 100%;
        height: calc(1.5em + .75rem + 2px);
        padding: .375rem .75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #6e707e;
        background-color: #fff;
        border: 1px solid #d1d3e2;
        border-radius: .35rem;
        transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
    }


    /* Overriding input and card fields */

    .form-control,
    .card,
    .btn {
        border-radius: 0 !important;
    }

    /* Overriding map height */

    #map_location {
        height: 340px !important;
    }



    .places-widget>input:first-child {
        width: 100% !important;
    }

    .places-widget>input:nth-child(2) {
        width: 39%;
        position: absolute;
        margin-bottom: 10px;
    }

    .places-widget>input:nth-child(3) {
        width: 50%;
        position: relative;
        float: right;
        margin-bottom: 10px;
    }

    .card {
        padding: 10px 10px 10px 10px;
        box-shadow: 0 19px 38px rgba(0, 0, 0, 0.30), 0 15px 12px rgba(0, 0, 0, 0.22);
    }


    input[type="checkbox"] {
        width: 20px !important;
        height: 20px !important;
        padding: 10px !important;
    }

    .form-check-label {
        margin-left: 10px;
        margin-top: 3px;
    }

    .profile-image {
        display: inline-block;
        width: 100px;
        height: 100px;
        border-radius: 50%;

        background-repeat: no-repeat;
        background-position: center center;
        background-size: cover;
        margin-bottom: 25px;
    }

    .hygiene-certificate-parent {
        width: 100%;
        max-height: 300px;
        overflow: scroll;
    }

    #previewFile {
        width: 100%;
        height: 400px;
        object-fit: contain;
        overflow: scroll;
    }

     @media only screen and (max-width: 600px) {
        .card-body {
            padding: 5px !important;
        }
    }
</style>
{% endblock %}
{% load bootstrap5 %}

{% block page %}
<div class="col-lg-offset-2 col-lg-12">
    <div class="card">
        <div class="card-body">
            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800">Account Information</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="profile-pic mt-3 mx-2">
                    <div class="mb-3 mx-1">
                        <div class="card shadow-sm row p-4 d-flex flex-row justify-content-between align-items-center">
                            <div>
                                <h3 class="pb-4">Profile Photo</h3> 
                                <div>
                                    {% if chef.picture.url != '' %}
                                    <img id="profile-image" src="{{ chef.picture.url  }}" alt="profile-picture"
                                        class="profile-image">

                                    {% else %}
                                    {% comment %} If there is no image, this is gonna be the default image {% endcomment %}
                                    <img id="profile-image" src="{% static 'img/empty-profile-pic.png' %}"
                                        alt="profile-picture" class="profile-image">

                                    {% endif %}
                                </div>
                                <div>
                                <label class="form-label" for="id_picture"></label>
                                <div class="custom-file">
                                    <input type="file" name="picture" accept="image/*"
                                        class="is-valid custom-file-input" title="" id="id_picture">
                                    <label class="custom-file-label" for="id_picture"
                                        aria-describedby="inputGroupFileAddon02">Choose file</label>
                                </div>
                            </div>
                            </div>
                            
                            
                            <div class="card shadow-sm p-4 mt-3 mt-md-0">
                                <h3>Photo Instructions </h3>
                                1. Ask someone to take a potrait photo of you.<br>
                                2. Take the photo during daylight or use studio lights.<br>
                                3. Look at the camera and smile!<br>
                                4. Don’t use a filter and don’t over edit the photo.
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row py-3">
                    <div class="personal-info col-lg-6 d-flex align-items-stretch">
                        <div class="card shadow-sm">
                            <h3 class="py-3 px-1 md:px-3 px-1">Personal Information</h3>
                            <div class="row px-1 md:px-3 px-1">
                                {% for field in user_form %}
                                <div class="col-lg-6">
                                    {% bootstrap_field field %}
                                </div>
                                {% endfor %}

                                <div class="col-lg-6">{% bootstrap_field chef_form.date_of_birth %}</div>
                                <div class="col-lg-12">{% bootstrap_field chef_form.gender %}</div>
                                <div class="col-lg-12">{% bootstrap_field chef_form.bio %}</div>
                            </div>
                        </div>
                    </div>

                    <div class="contact-info col-lg-6">
                        <div class="card shadow-sm">
                            <h3 class="py-3 px-md-3 px-1">Contact Information</h3>
                            <div class="row px-md-3 px-1">
                                <div class="col-lg-6">{% bootstrap_field chef_form.phone %}</div>
                                <div class="col-lg-6">{% bootstrap_field chef_form.chef_flat_number %}</div>
                                <div class="col-lg-6">{% bootstrap_field chef_form.city %}</div>
                                <div class="col-lg-6">{% bootstrap_field chef_form.postcode %}</div>
                                <div class="col-lg-12">{% bootstrap_field chef_form.chef_street_address %}</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="kitchen-info px-2 mx-1">
                    <div class="row card shadow-sm">
                        <h3 class="py-3 px-md-3 px-1">Chef Information</h3>
                        <div class="row px-md-3 px-1">
                            <div class="col-lg-4">
                                <div class="mb-3"><label class="form-label" for="id_name">Chef name</label><input
                                        type="text" name="name" value="{{ chef.name }}" maxlength="500"
                                        class="form-control" placeholder="Chef Elon" title="" id="id_name">
                                </div>
                            </div>
                            <div class="col-lg-4">{% bootstrap_field chef_form.cuisine %}</div>
                            <div class="col-lg-4">{% bootstrap_field chef_form.delivery_time %}</div>



                            <div class="col-lg-4">
                                <div class="mb-3 is-valid">
                                    <label class="form-label" for="id_level_2_food_hygiene_certificate">Level 2 food
                                        hygiene
                                        certificate</label>
                                    <div class="custom-file">
                                        <input type="file" name="level_2_food_hygiene_certificate"
                                            class="is-valid custom-file-input" title=""
                                            id="id_level_2_food_hygiene_certificate">
                                        <label class="custom-file-label" for="id_level_2_food_hygiene_certificate"
                                            aria-describedby="inputGroupFileAddon02">Choose file</label>
                                        {% if chef.level_2_food_hygiene_certificate.url != '' %}
                                        <div id="hygiene-certificate">Current: <a href="{{ chef.level_2_food_hygiene_certificate.url }}"
                                                target="_blank">{{chef.level_2_food_hygiene_certificate }}</a></div>
                                        {% endif %}

                                        <!-- Button trigger modal -->
                                        <button id="see-preview" type="button" class="btn btn-primary my-3" data-toggle="modal" data-target="#exampleModal">
                                        Show Preview
                                        </button>
                                    </div>  
                                </div>
                            </div>
                            <div class="col-lg-4 pt-4">
                            <div class="pt-3">
                                {% bootstrap_field chef_form.authorized_to_work_in_the_UK %}
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="py-3">
                    <button type="submit" class="px-md-3 px-1 py-2 btn btn-primary mt-2 me-2">Update Account</button>
                    {{ chef_form.media }}
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'authorize' %}" class="px-md-3 px-1 py-2 btn btn-primary mt-2">Payment & Payouts</a>
                    {% endif %}
                </div>

            </form>
        </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Preview Window</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <embed src="" id="previewFile" /> 
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
    </div>
</div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script>
    document.getElementById('see-preview').style.display = "none";

    $("#id_picture").change(function (e) {

        for (var i = 0; i < e.originalEvent.srcElement.files.length; i++) {

            var file = e.originalEvent.srcElement.files[i];

            var img = document.getElementById("profile-image");
            var reader = new FileReader();
            reader.onloadend = function () {
                img.src = reader.result;
            }
            reader.readAsDataURL(file);
        }
    });

    $("#id_level_2_food_hygiene_certificate").change(function (e) {

        document.getElementById('see-preview').style.display = "block";

        for (var i = 0; i < e.originalEvent.srcElement.files.length; i++) {

            var file = e.originalEvent.srcElement.files[i];

            var img = document.getElementById("previewFile");
            var reader = new FileReader();
            reader.onloadend = function () {
                img.src = reader.result;
            }
            reader.readAsDataURL(file);
        }
    });
    

</script>

{% endblock %}

urbanshef/templates/chef/login.html
{% extends 'base_login.html' %}
{% load bootstrap5 %}

{% block title %}Sign in - Slobite {% endblock %}
{% block heading %}Sign in - Chef Account{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %} role="alert">{{ message }}</div>
            {% endfor %}
    {% endif %}

    <form method="POST" class="login-form mt-4">
        {% csrf_token %}
        <div class="col-lg-12">
            <div class="mb-3">
                <label class="form-label">Username or Email <span class="text-danger">*</span></label>
                <div class="form-icon position-relative">
                    <i data-feather="user" class="fea icon-sm icons"></i>
                    <input type="text" class="form-control ps-5" placeholder="chefelon" name="username" required="">
                </div>
            </div>
        </div> <!--end col-->
        <div class="col-lg-12">
            <div class="mb-3">
                <label class="form-label">Password <span class="text-danger">*</span></label>
                <div class="form-icon position-relative">
                    <i data-feather="key" class="fea icon-sm icons"></i>
                    <input type="password" class="form-control ps-5" placeholder="Password" required="" name="password">
                </div>
            </div>
        </div><!--end col-->
        <div class="mx-auto">
            <div class="d-flex justify-content-between">
                <div class="mb-3">
                    <div class="mx-auto">
                        <!-- <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">Remember me</label> -->
                        <p class="forgot-pass mb-0"><a href="{% url 'reset_password' %}" class="text-dark fw-bold">Forgot
                            password ?</a></p>
                    </div>
                </div>

            </div>
        </div><!--end col-->

        <div class="col-lg-12 mb-0">
            <div class="d-grid">
                <button type="submit" class="btn btn-primary">Sign in</button>
            </div>
        </div><!--end col-->
    </form>
    <div class="col-12 text-center">
        <p class="mb-0 mt-3"><small class="text-dark me-2">Love cooking?</small><a href="{% url 'chef-sign-up' %}"
                                                                                   class="text-dark fw-bold">Become a
            chef</a></p>
    </div><!--end col-->

{% endblock %}

urbanshef/templates/chef/password_reset_done.html
{% extends 'base_login.html' %}
{% load bootstrap5 %}

{% block title %}Password reset finished! - Slobite{% endblock %}
{% block heading %}Password reset finished!{% endblock %}

{% block content %}

    <p>Your password has been set. You may go ahead and log in now.</p>
    <a href="{% url 'chef-login' %}">Already have an account?</a>

{% endblock %}